Feature: Creating Comment
  As a user, I want to add a comment to an existing bug

  Scenario: Successful comment creation
    Given I am logged in as John Smith
    When I click on the first bug
    And I input a comment
    And I press the submit button
    Then I should see my comment

  Scenario Outline: Unsuccessful comment creation
    Given I am logged in as John Smith
    When I click on the first bug
    And I input "<text>" as a comment
    And I press the submit button
    Then I should see an alert

    Examples:
      | text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | empty                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
      | lol no                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
      | unhelpful                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long. This comment will be very long.|

